# Generated by Django 5.1.5 on 2025-04-22 07:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Compte',
            },
        ),
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id_objet', models.AutoField(primary_key=True, serialize=False)),
                ('nom_objet', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Objet',
            },
        ),
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('id_data', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('hdop', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('course', models.FloatField(blank=True, null=True)),
                ('sats', models.IntegerField(blank=True, null=True)),
                ('id_objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt_app.objet')),
            ],
            options={
                'db_table': 'Donnee2',
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt_app.compte')),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt_app.objet')),
            ],
            options={
                'db_table': 'affectation',
                'unique_together': {('utilisateur', 'objet')},
            },
        ),
    ]
